import json
import logging
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
import time

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger("BroadcastServer")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CLUSTER_STATE_FILE = PROJECT_ROOT / "vaults" / "cluster_state.json"
ROUTING_MAP_FILE = PROJECT_ROOT / "vaults" / "optimized_routing.json"

# Feature Controls
ENABLE_DYNAMIC_RETRY_AFTER = True
MIN_RETRY_AFTER = 1
MAX_RETRY_AFTER = 60

class BackpressureHTTPHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        # Suppress standard HTTP logging to keep telemetry clean
        return

    def _load_routing_decision(self):
        """Reads the cached structural decisions generated by the orchestrator."""
        if ROUTING_MAP_FILE.exists():
            try:
                with open(ROUTING_MAP_FILE, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except:
                pass
        return {"global_action": "NOMINAL", "calculated_drain_rates": {}}

    def _load_current_depths(self):
        """Reads the raw current state lane depths across workers."""
        if CLUSTER_STATE_FILE.exists():
            try:
                with open(CLUSTER_STATE_FILE, 'r', encoding='utf-8') as f:
                    return json.load(f).get("worker_diagnostics", {})
            except:
                pass
        return {}

    def do_POST(self):
        routing = self._load_routing_decision()
        state = routing.get("global_action", "NOMINAL")
        
        # Extract headers to detect priority bypass traffic
        is_priority = self.headers.get("X-Priority-Traffic", "false").lower() == "true"

        # Circuit Breaker Logic Tree
        if state == "THROTTLE_INGESTION":
            # Total lockdown: Reject everything
            self._apply_backpressure(routing, priority_breach=True)
            return

        elif state == "SHED_LOAD":
            if is_priority:
                # High priority lane bypass allowed
                self._serve_success()
            else:
                # Saturated standard lane: Apply targeted dynamic backpressure
                self._apply_backpressure(routing, priority_breach=False)
            return

        # Default Nominal State Handling
        self._serve_success()

    def _serve_success(self):
        self.send_response(202)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(b'{"status": "ACCEPTED", "message": "Payload queued for lane execution."}')

    def _apply_backpressure(self, routing, priority_breach=False):
        """Calculates dynamic client-side backpressure timeouts based on EMA rates."""
        retry_after = 5 # Absolute fallback window if files are corrupted
        
        if ENABLE_DYNAMIC_RETRY_AFTER and not priority_breach:
            diagnostics = self._load_current_depths()
            # Default lookup target for single cluster verification setup
            worker_id = "Worker-00" 
            
            worker_stats = diagnostics.get(worker_id, {})
            std_lane_depth = worker_stats.get("standard_lane_depth", 0)
            
            drain_rates = routing.get("calculated_drain_rates", {})
            worker_ema_drain = drain_rates.get(worker_id, 50.0)

            if worker_ema_drain > 0:
                # Core Equation: Wait Time = Depth / Processing Speed
                calculated_wait = int(std_lane_depth / worker_ema_drain)
                retry_after = min(MAX_RETRY_AFTER, max(MIN_RETRY_AFTER, calculated_wait))
        elif priority_breach:
            # Under total lockdown, enforce a long systemic cooling window
            retry_after = 30

        self.send_response(503)
        self.send_header("Content-Type", "application/json")
        self.send_header("Retry-After", str(retry_after))
        self.end_headers()
        
        response_body = {
            "status": "REJECTED",
            "reason": "THROTTLE_INGESTION" if priority_breach else "SHED_LOAD",
            "suggested_backoff_seconds": retry_after
        }
        self.wfile.write(json.dumps(response_body).encode('utf-8'))

def run_server(port=8090):
    server_address = ('', port)
    httpd = HTTPServer(server_address, BackpressureHTTPHandler)
    logger.info(f"🖥️ Edge Ingestion Gateway with Adaptive Backpressure running on port {port}...")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()

if __name__ == "__main__":
    run_server()
